/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.ConectorMySQL;
import Backend.ConfiguracionesGenerales;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author astridmc
 */
public class Principal extends javax.swing.JFrame {

    //1=rbtnHorarioContratacion,2=rbtnSemActual,3=rbtnSemestreAlto,4=rbtnSemestreBajo
   public static int configuracion=1;
    ConectorMySQL conn ;
    TablaProfesores profesores;
    TablaSalones salones;
    TablaCursos cursos;
    TablaAsignaciones asignaciones;
    GenerarHorario generarH;
    ConfiguracionesGenerales conf;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conn =  new ConectorMySQL("usuarioHorarios", "Horarios.123");
        conn.conector();
        setTitle("GENERADOR DE HORARIOS");
        setIconImage(new ImageIcon("horario.png").getImage());
        conf= new ConfiguracionesGenerales();
         conf.llenarConfiguraciones(ConectorMySQL.conexion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        panelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnGenerar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnTablaProfesores = new javax.swing.JMenuItem();
        btnTablaCursoProfesor = new javax.swing.JMenuItem();
        btnTablaCursos = new javax.swing.JMenuItem();
        btnTablaAsignaciones = new javax.swing.JMenuItem();
        btnTablaSalones = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(229, 230, 255));
        panelPrincipal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panelPrincipalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(60,63,65));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Generar");

        btnGenerar.setText("Nuevo Horario");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jMenu1.add(btnGenerar);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Configuraciones");

        jMenuItem3.setText("Priorizacion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setText("Ver");

        btnTablaProfesores.setText("Profesores");
        btnTablaProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaProfesoresActionPerformed(evt);
            }
        });
        jMenu3.add(btnTablaProfesores);

        btnTablaCursoProfesor.setText("CursoProfesor");
        btnTablaCursoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaCursoProfesorActionPerformed(evt);
            }
        });
        jMenu3.add(btnTablaCursoProfesor);

        btnTablaCursos.setText("Cursos");
        btnTablaCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaCursosActionPerformed(evt);
            }
        });
        jMenu3.add(btnTablaCursos);

        btnTablaAsignaciones.setText("Asignaciones");
        btnTablaAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaAsignacionesActionPerformed(evt);
            }
        });
        jMenu3.add(btnTablaAsignaciones);

        btnTablaSalones.setText("Salones");
        btnTablaSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaSalonesActionPerformed(evt);
            }
        });
        jMenu3.add(btnTablaSalones);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
       generarH = new  GenerarHorario ();
       LlenarPanel(generarH);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnTablaProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaProfesoresActionPerformed
       profesores =new TablaProfesores();
       
        LlenarPanel(profesores);
        
    }//GEN-LAST:event_btnTablaProfesoresActionPerformed

    private void panelPrincipalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panelPrincipalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPrincipalPropertyChange

    private void btnTablaCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaCursosActionPerformed
          cursos=new TablaCursos();
        LlenarPanel(cursos);
    }//GEN-LAST:event_btnTablaCursosActionPerformed

    private void btnTablaSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaSalonesActionPerformed
        salones =new TablaSalones();
        LlenarPanel(salones);
    }//GEN-LAST:event_btnTablaSalonesActionPerformed

    private void btnTablaCursoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaCursoProfesorActionPerformed
        TblCursoProfesor tablaCursoProfesor = new TblCursoProfesor(this, false);
        tablaCursoProfesor.setVisible(true);
    }//GEN-LAST:event_btnTablaCursoProfesorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Priorizaciones prio = new Priorizaciones(this,false);
        prio.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnTablaAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaAsignacionesActionPerformed
         asignaciones= new TablaAsignaciones();
        LlenarPanel(asignaciones);
    }//GEN-LAST:event_btnTablaAsignacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new Principal().setVisible(true);
            }
        });
    }
    
    public void LlenarPanel (JPanel panel){
         panelPrincipal.removeAll();
        panelPrincipal.setLayout(new java.awt.BorderLayout());
        panel.setSize(panelPrincipal.getWidth(), panelPrincipal.getHeight());
        panelPrincipal.add(panel);
        panel.setVisible(true);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnGenerar;
    private javax.swing.JMenuItem btnTablaAsignaciones;
    private javax.swing.JMenuItem btnTablaCursoProfesor;
    private javax.swing.JMenuItem btnTablaCursos;
    private javax.swing.JMenuItem btnTablaProfesores;
    private javax.swing.JMenuItem btnTablaSalones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
