/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.ConectorMySQL;
import Backend.Curso;
import Backend.Salon;
import java.util.ArrayList;

/**
 *
 * @author astridmc
 */
public class TablaSalones extends javax.swing.JPanel {

    /**
     * Creates new form TablaProfesores
     */
    public TablaSalones() {
        initComponents();
        ListarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(1, 35, 70));

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("SALONES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idSalon", "Capacidad", "PorcentajeSobrecarga", "CursoDefinido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void ListarCursos(){
               Salon  salon = new Salon();
               ArrayList<Salon> salones = salon.ListarSalones(ConectorMySQL.conexion);
               Object[][] salonesTBL = new Object[salones.size()][5];
               int i = 0;
                for (Salon salonL: salones) {
                            //Object[] fila = new Object[profesores.size()];
                            salonesTBL[i][0] = salonL.getIdSalon();
                            salonesTBL[i][1] = salonL.getCapacidad();
                            salonesTBL[i][2] = salonL.getPorcentajeSoreCarga();
                            salonesTBL[i][3] = salonL.getCursoDef();
                           
                            //model.addRow(fila);
                            i++;
                }
                jTable1.setModel(new javax.swing.table.DefaultTableModel( salonesTBL,    
                        new String [] { "idSalon", "Capacidad", "PorcentajeSobrecarga", "CursoDefinido"} ));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
