/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.ConectorMySQL;
import Backend.Profesor;
import java.util.ArrayList;

/**
 *
 * @author astridmc
 */
public class TablaProfesores extends javax.swing.JPanel {

    /**
     * Creates new form TablaProfesores
     */
    public TablaProfesores() {
        initComponents();
        ListarProfesores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(1, 35, 70));

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("PROFESORES");
        jLabel1.setToolTipText("");

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idProfesor", "Nombre", "HoraInicio", "HoraFin", "Detalles"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void ListarProfesores(){
                  Profesor profesor = new Profesor();
               ArrayList<Profesor> profesores = profesor.ProfesoresListado(ConectorMySQL.conexion);
               Object[][] profesoresTbl = new Object[profesores.size()][5];
               int i = 0;
                for (Profesor prof: profesores) {
                            //Object[] fila = new Object[profesores.size()];
                            profesoresTbl[i][0] = prof.getIdProfesor();
                            profesoresTbl[i][1] = prof.getNombre();
                            profesoresTbl[i][2] = prof.getHoraEntrada();
                            profesoresTbl[i][3] = prof.getHoraSalida();
                            if(prof.isDescanso()){
                                   profesoresTbl[i][4] = "No Activo" ;
                            }else{
                                   profesoresTbl[i][4] = "Activo" ;
                            }
                            //model.addRow(fila);
                            i++;
                }
                jTable1.setModel(new javax.swing.table.DefaultTableModel( profesoresTbl,    
                        new String [] { "idProfesor", "Nombre", "HoraInicio", "HoraFin", "Activo" } ));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
