/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Asignacion;
import Backend.ConectorMySQL;
import Backend.Salon;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author astridmc
 */
public class TablaAsignaciones extends javax.swing.JPanel {

    Asignacion asignacion = new Asignacion();

    /**
     * Creates new form TablaProfesores
     */
    public TablaAsignaciones() {
        initComponents();
        confComboFechas();
        llenarAsignaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboFechas = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(1, 35, 70));

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Fecha");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FechaAsignacion", "IdCursoSeccion", "IdCurso", "NumeroAsignados", "tipoSemestre"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("ASIGNACIONES");

        comboFechas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFechasActionPerformed
        llenarAsignaciones();
    }//GEN-LAST:event_comboFechasActionPerformed

    public void confComboFechas() {
        ArrayList<String> fechas = asignacion.listarFechasAsignacion(ConectorMySQL.conexion);
        String[] fechasA = new String[fechas.size()];
        for (int i = 0; i < fechas.size(); i++) {
            fechasA[i] = fechas.get(i);
        }
        comboFechas.setModel(new javax.swing.DefaultComboBoxModel<>(fechasA));
    }

    public void llenarAsignaciones() {
        Asignacion asignacion = new Asignacion();
        String fechaSel = comboFechas.getSelectedItem().toString();


            ArrayList<Asignacion> asignaciones = asignacion.listarAsignaciones(ConectorMySQL.conexion, fechaSel);
            Object[][] salonesTBL = new Object[asignaciones.size()][6];
            int i = 0;
            for (Asignacion asig : asignaciones) {
                //Object[] fila = new Object[profesores.size()];
                salonesTBL[i][0] = asig.getFechaAsignacion();
                salonesTBL[i][1] = asig.getIdCurso();
                salonesTBL[i][2] = asig.getNombreCurso();
                salonesTBL[i][3] = asig.getSeccion();
                salonesTBL[i][4] = asig.getNumeroAsignados();
                salonesTBL[i][5] = asig.getSemestre();
                //model.addRow(fila);
                i++;
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(salonesTBL,
                    new String[]{"fechaAsignacion", "idCurso", "nombreCurso", "seccion", "numero Asignados", "semestre"}));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFechas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
