/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.ConectorMySQL;
import Backend.Curso;
import Backend.Profesor;
import java.util.ArrayList;

/**
 *
 * @author astridmc
 */
public class TablaCursos extends javax.swing.JPanel {

    /**
     * Creates new form TablaCursos
     */
    public TablaCursos() {
        initComponents();
         ListarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(1, 35, 70));

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("CURSOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idCurso", "Nombre", "Carrera", "Semestre ", "tipoSemestre"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void ListarCursos(){
               Curso curso = new Curso();
               ArrayList<Curso> cursos = curso.ListarCursos(ConectorMySQL.conexion);
               Object[][] profesoresTbl = new Object[cursos.size()][5];
               int i = 0;
                for (Curso cursoL: cursos) {
                            //Object[] fila = new Object[profesores.size()];
                            profesoresTbl[i][0] = cursoL.getIdCurso();
                            profesoresTbl[i][1] = cursoL.getNombreCurso();
                            profesoresTbl[i][2] = cursoL.getCarrera();
                            profesoresTbl[i][3] = cursoL.getTipoSemestre();
                            if(cursoL.getTipoSemestre()==1){
                                   profesoresTbl[i][4] = "Impar";
                            }else{
                                   profesoresTbl[i][4] = "Par";
                            }
                            //model.addRow(fila);
                            i++;
                }
                jTable1.setModel(new javax.swing.table.DefaultTableModel( profesoresTbl,    
                        new String [] {"idCurso", "Nombre", "Carrera", "Semestre ", "tipoSemestre"} ));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
